### ISSUE TITLE
CSS Tutorial - PATCH updates return 501

### ISSUE THREAD

**Issue by MisterTimn** [KNowledgeOnWebScale/solid-linked-data-workshops-hands-on-exercises#11]
When following along with the tutorial for CSS, the SPARQL update returns a 501
[Relevant line in tutorial](https://github.com/KNowledgeOnWebScale/solid-linked-data-workshops-hands-on-exercises/blob/main/css-tutorial.md#patching-resources)

This is using version 3.0.0, the latest commit on CSS repo ([46132da8c29dc05242ae035203b478f8be325083](https://github.com/CommunitySolidServer/CommunitySolidServer/commit/46132da8c29dc05242ae035203b478f8be325083))

```bash
$ curl http://localhost:3000/a/b/c
<ex:s> <ex:p> <ex:o>.
```

```bash
$ curl -X PATCH -H "Content-Type: application/sparql-update" -d "INSERT DATA { <ex:s3> <ex:p3> <ex:o3> }" http://localhost:3000/a/b/c
{"name":"NotImplementedHttpError","message":"No conversion path could be made from text/turle to internal/quads:1,internal/*:0.","statusCode":501,"errorCode":"H501","stack":"NotImplementedHttpError: No conversion path could be made from text/turle to internal/quads:1,internal/*:0.\n    at ChainedConverter.generatePath (/home/jveessen/SolidLab/CommunitySolidServer/dist/storage/conversion/ChainedConverter.js:103:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ChainedConverter.handle (/home/jveessen/SolidLab/CommunitySolidServer/dist/storage/conversion/ChainedConverter.js:49:23)\n    at async ConvertingPatcher.handle (/home/jveessen/SolidLab/CommunitySolidServer/dist/storage/patch/ConvertingPatcher.js:55:25)\n    at async RepresentationPatchHandler.handle (/home/jveessen/SolidLab/CommunitySolidServer/dist/storage/patch/RepresentationPatchHandler.js:36:25)\n    at async runWithTimeout (/home/jveessen/SolidLab/CommunitySolidServer/dist/util/locking/WrappedExpiringReadWriteLocker.js:51:24)\n    at async GreedyReadWriteLocker.withWriteLock (/home/jveessen/SolidLab/CommunitySolidServer/dist/util/locking/GreedyReadWriteLocker.js:48:20)\n    at async MonitoringStore.modifyResource (/home/jveessen/SolidLab/CommunitySolidServer/dist/storage/MonitoringStore.js:32:33)\n    at async PatchOperationHandler.handle (/home/jveessen/SolidLab/CommunitySolidServer/dist/http/ldp/PatchOperationHandler.js:39:9)\n    at async ParsingHttpHandler.handle (/home/jveessen/SolidLab/CommunitySolidServer/dist/server/ParsingHttpHandler.js:28:22)\n    at async SequenceHandler.handle (/home/jveessen/SolidLab/CommunitySolidServer/dist/util/handlers/SequenceHandler.js:27:26)\n    at async Server.<anonymous
```

More readable output
```json
{
  "name": "NotImplementedHttpError",
  "message": "No conversion path could be made from text/turle to internal/quads:1,internal/*:0.",
  "statusCode": 501,
  "errorCode": "H501",
  "stack": "NotImplementedHttpError: No conversion path could be made from text/turle to internal/quads:1,internal/*:0.\n    at ChainedConverter.generatePath (/home/jveessen/SolidLab/CommunitySolidServer/dist/storage/conversion/ChainedConverter.js:103:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ChainedConverter.handle (/home/jveessen/SolidLab/CommunitySolidServer/dist/storage/conversion/ChainedConverter.js:49:23)\n    at async ConvertingPatcher.handle (/home/jveessen/SolidLab/CommunitySolidServer/dist/storage/patch/ConvertingPatcher.js:55:25)\n    at async RepresentationPatchHandler.handle (/home/jveessen/SolidLab/CommunitySolidServer/dist/storage/patch/RepresentationPatchHandler.js:36:25)\n    at async runWithTimeout (/home/jveessen/SolidLab/CommunitySolidServer/dist/util/locking/WrappedExpiringReadWriteLocker.js:51:24)\n    at async GreedyReadWriteLocker.withWriteLock (/home/jveessen/SolidLab/CommunitySolidServer/dist/util/locking/GreedyReadWriteLocker.js:48:20)\n    at async MonitoringStore.modifyResource (/home/jveessen/SolidLab/CommunitySolidServer/dist/storage/MonitoringStore.js:32:33)\n    at async PatchOperationHandler.handle (/home/jveessen/SolidLab/CommunitySolidServer/dist/http/ldp/PatchOperationHandler.js:39:9)\n    at async ParsingHttpHandler.handle (/home/jveessen/SolidLab/CommunitySolidServer/dist/server/ParsingHttpHandler.js:28:22)\n    at async SequenceHandler.handle (/home/jveessen/SolidLab/CommunitySolidServer/dist/util/handlers/SequenceHandler.js:27:26)\n    at async Server.<anonymous> (/home/jveessen/SolidLab/CommunitySolidServer/dist/server/BaseHttpServerFactory.js:33:17)"
}
```

**Comment by pheyvaer** [comment]
Hi @MisterTimn 

Is this an error in the tutorial or CSS then?

**Comment by joachimvh** [comment]
Just tried this out myself and everything worked as expected so I can't reproduce. The error is strange though. The server is saying it has no way to convert turtle to quads, meaning it somehow can't find its `RdfToQuadConverter`. Can't immediately say what could cause this.

**Comment by MisterTimn** [comment]
I only get this behavior when first creating http://localhost:3000/a/b/c through Thunder Client (VS Code extension cf. Postman) then performing the PATCH request. When I use the curl statement to PUT it works as intended.

Both PUT requests seem to be identical... Here is a screenshot from the request in VS Code
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/4209558/161535590-ee83be65-7194-4f02-b9cb-1300c3b82027.png">

This is the translation of the request to curl according to the extension
<img width="498" alt="image" src="https://user-images.githubusercontent.com/4209558/161535894-0c8bad67-bc01-44fd-9db4-d1952128508d.png">

**Comment by RubenVerborgh** [comment]
Can we have a `curl -i http://localhost:3000/a/b/c`?

**Comment by joachimvh** [comment]
I have just retried with postman itself (as I don't have VS Code) doing the 2 PUTs of the tutorial and then the PATCH and was successful. 

Something else that can perhaps help debug: can you start the server with a file backend (using `-c config/file-no-setup.json`) and inspect which files were created by the PUT? It should be `a/b/c$.ttl`.

At this point I'm wondering if somehow there is a non-standard character in `text/turtle` which causes the type match to fail.

**Comment by MisterTimn** [comment]
Ok sorry for wasting your time, as suspected by @joachimvh there `tex/turtle` header had a typo which I failed to detect. Tutorial is fine and so is the CSS

**Comment by RubenVerborgh** [comment]
`text/turle` tricky 😃
